kind: Service
apiVersion: v1
metadata:
  name: ovn-sb
  namespace: kube-system
spec:
  ports:
    - name: ovn-sb
      protocol: TCP
      port: 6642
      targetPort: 6642
  type: ClusterIP
  {{- if eq .Values.networking.net_stack "dual_stack" }}
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  selector:
    app: ovn-central
    ovn-sb-leader: "true"
  sessionAffinity: None
