# Default values for kubeovn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  registry:
    address: kubeovn
    imagePullSecrets: []
  images:
    kubeovn:
      repository: kube-ovn
      tag: v1.11.0
      support_arm: true
      thirdparty: true

image:
  pullPolicy: IfNotPresent

replicaCount: 1
MASTER_NODES: ""

networking:
  # NET_STACK could be dual_stack, ipv4, ipv6
  NET_STACK: ipv4
  ENABLE_SSL: false
  # network type could be geneve or vlan
  NETWORK_TYPE: geneve
  # tunnel type could be geneve, vxlan or stt
  TUNNEL_TYPE: geneve
  IFACE: ""
  DPDK_TUNNEL_IFACE: "br-phy"
  EXCLUDE_IPS: ""
  POD_NIC_TYPE: "veth-pair"
  vlan:
    VLAN_INTERFACE_NAME: ""
    VLAN_NAME: "ovn-vlan"
    VLAN_ID: "100"
  EXCHANGE_LINK_NAME: false
  ENABLE_EIP_SNAT: true
  POD_DEFAULT_FIP_TYPE: ""

func:
  ENABLE_LB: true
  ENABLE_NP: true
  ENABLE_EIP_SNAT: true
  ENABLE_EXTERNAL_VPC: true
  HW_OFFLOAD: false
  ENABLE_LB_SVC: false
  ENABLE_KEEP_VM_IP: true
  LS_DNAT_MOD_DL_DST: true
  CHECK_GATEWAY: true
  LOGICAL_GATEWAY: false

ipv4:
  POD_CIDR: "10.16.0.0/16"
  POD_GATEWAY: "10.16.0.1"
  SVC_CIDR: "10.96.0.0/12"
  JOIN_CIDR: "100.64.0.0/16"
  PINGER_EXTERNAL_ADDRESS: "114.114.114.114"
  PINGER_EXTERNAL_DOMAIN: "alauda.cn"

ipv6:
  POD_CIDR: "fd00:10:16::/64"
  POD_GATEWAY: "fd00:10:16::1"
  SVC_CIDR: "fd00:10:96::/112"
  JOIN_CIDR: "fd00:100:64::/64"
  PINGER_EXTERNAL_ADDRESS: "2400:3200::1"
  PINGER_EXTERNAL_DOMAIN: "google.com"

dual_stack:
  POD_CIDR: "10.16.0.0/16,fd00:10:16::/64"
  POD_GATEWAY: "10.16.0.1,fd00:10:16::1"
  SVC_CIDR: "10.96.0.0/12,fd00:10:96::/112"
  JOIN_CIDR: "100.64.0.0/16,fd00:100:64::/64"
  PINGER_EXTERNAL_ADDRESS: "114.114.114.114,2400:3200::1"
  PINGER_EXTERNAL_DOMAIN: "google.com"

performance:
  MODULES: "kube_ovn_fastpath.ko"
  RPMS: "openvswitch-kmod"
  GC_INTERVAL: 360
  INSPECT_INTERVAL: 20

debug:
  ENABLE_MIRROR: false

cni_conf:
  CNI_CONFIG_PRIORITY: "01"
  CNI_CONF_DIR: "/etc/cni/net.d"
  CNI_BIN_DIR: "/opt/cni/bin"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

