kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-config
  namespace: {{ .Values.namespace }}
data:
  image: {{ .Values.natGw.image.repository }}:{{ .Values.natGw.image.tag }}
  {{- with .Values.natGw.bgpSpeaker.image }}
  bgpSpeakerImage: {{ .repository }}:{{ .tag }}
  {{- end }}
  {{- with .Values.natGw.bgpSpeaker.apiNadProvider }}
  apiNadProvider: {{ tpl . $ }}
  {{- end }}
  {{- with .Values.natGw.namePrefix }}
  natGwNamePrefix: {{ . | quote }}
  {{- end }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ovn-vpc-nat-gw-config
  namespace: {{ .Values.namespace }}
data:
  enable-vpc-nat-gw: "{{ .Values.features.enableNatGateways }}"