name: Publish Release
on:
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Publish Images
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Publish
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          TAG=$(cat VERSION)
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker pull kubeovn/kube-ovn:$TAG-x86
          docker pull kubeovn/kube-ovn:$TAG-arm
          docker manifest create kubeovn/kube-ovn:$TAG kubeovn/kube-ovn:$TAG-x86 kubeovn/kube-ovn:$TAG-arm
          docker manifest push kubeovn/kube-ovn:$TAG

          docker pull kubeovn/vpc-nat-gateway:$TAG-x86
          docker pull kubeovn/vpc-nat-gateway:$TAG-arm
          docker manifest create kubeovn/vpc-nat-gateway:$TAG kubeovn/vpc-nat-gateway:$TAG-x86 kubeovn/vpc-nat-gateway:$TAG-arm
          docker manifest push kubeovn/vpc-nat-gateway:$TAG
